pub mod analysis;
#[cfg(feature = "cache")]
pub mod caching;
pub mod config;
pub mod data;
pub mod diagnostic;
pub mod directives;
pub mod exit;
pub mod formatting;
pub mod git;
pub mod install;
pub mod languages;
#[cfg(feature = "lsp")]
pub mod lsp;
#[cfg(feature = "mcp")]
pub mod mcp;
pub mod options;
pub mod output;
pub mod processing;
pub mod scanning;
pub mod schemas;
pub mod secrets;
pub mod shared;
pub mod source;
pub mod text;
pub mod trestlerc;
pub mod watch;
